sequenceDiagram
    title Log Flow
    autonumber

SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (1.9ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (2.2ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (2.3ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (1.9ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (3.5ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (2.1ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (3.4ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (3.0ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (2.2ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (4.4ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (2.2ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (3.2ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (2.1ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (3.2ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (2.2ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (2.3ms)
SyncClient->>TestAPI: GET /sync-ok
TestAPI-->>SyncClient: Return: 200 (3.1ms)
