"""
FastAPI Integration Module for MermaidTrace.

This module provides the middleware necessary to integrate MermaidTrace with
FastAPI applications. It serves as the bridge between HTTP requests and the
sequence diagram generation logic.

Key functionalities include:
- Middleware for intercepting all incoming HTTP requests.
- Automatic extraction of tracing headers (X-Source, X-Trace-ID, traceparent).
- Initialization of logging context for request lifecycles.
- Automatic logging of request start and response completion (success or error).
"""

from typing import Any, TYPE_CHECKING
import time
import uuid
import traceback
import random

from ..core.events import FlowEvent
from ..core.context import LogContext
from ..core.decorators import get_flow_logger
from ..core.config import config
from ..core.sanitizer import data_masker

# Conditional imports to support optional FastAPI dependency
if TYPE_CHECKING:
    # For static type checkers (mypy, pyright), import the actual types.
    from fastapi import Request, Response
    from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
else:
    try:
        # Runtime import attempt for FastAPI and Starlette.
        from fastapi import Request, Response
        from starlette.middleware.base import (
            BaseHTTPMiddleware,
            RequestResponseEndpoint,
        )
    except ImportError:
        # Fallback for when FastAPI is not installed in the environment.
        # This prevents ImportErrors when importing this module without FastAPI.
        # However, instantiating the middleware will still fail.
        BaseHTTPMiddleware = object  # type: ignore[misc,assignment]
        Request = Any  # type: ignore[assignment]
        Response = Any  # type: ignore[assignment]
        RequestResponseEndpoint = Any  # type: ignore[assignment]


class MermaidTraceMiddleware(BaseHTTPMiddleware):
    """
    FastAPI Middleware to trace HTTP requests as interactions in the sequence diagram.

    This middleware wraps the entire request processing pipeline. It is responsible for
    recording the initial interaction between an external client (Source) and this
    service (Target).

    Middleware Logic:
    1.  **Request Interception**: Captures the request before it reaches any route handler.
    2.  **Context Initialization**: Sets up the `LogContext` with the current service name
        and trace ID, ensuring all internal function calls are correctly associated.
    3.  **Event Logging**: Logs the "Request" event (Client -> API) and the corresponding
        "Response" event (API -> Client).
    4.  **Error Handling**: Captures exceptions, logs error events (API --x Client),
        and re-raises them to standard error handlers.

    Attributes:
        app_name (str): The name of the current service/application. This name will
                        appear as a participant in the generated Mermaid sequence diagram.
    """

    def __init__(self, app: Any, app_name: str = "FastAPI"):
        """
        Initialize the middleware.

        Args:
            app (Any): The FastAPI application instance.
            app_name (str): The name of this service to appear in the diagram (e.g., "UserAPI").
                            Defaults to "FastAPI".

        Raises:
            ImportError: If FastAPI or Starlette is not installed in the current environment.
        """
        # Validate that the necessary dependencies are present.
        if BaseHTTPMiddleware is object:  # type: ignore[comparison-overlap]
            raise ImportError(
                "FastAPI/Starlette is required to use MermaidTraceMiddleware"
            )

        # Initialize the base class.
        super().__init__(app)
        self.app_name = app_name

    async def dispatch(
        self, request: Request, call_next: RequestResponseEndpoint
    ) -> Response:
        """
        Dispatch method to handle the incoming request.

        This is the core logic of the middleware. It wraps the `call_next` execution
        with tracing logic.

        Request Tracing & Header Handling:
        - **X-Source**: Used to identify the caller. If present, the diagram will show
          an arrow from `X-Source` to `app_name`. If missing, defaults to "Client".
        - **X-Trace-ID**: Used for distributed tracing. If provided, it links this
          request to an existing trace. If missing, a new UUID is generated.

        Args:
            request (Request): The incoming HTTP request object.
            call_next (RequestResponseEndpoint): A callable that invokes the next
                                                 middleware or the route handler.

        Returns:
            Response: The HTTP response generated by the application.
        """
        # ----------------------------------------------------------------------
        # 1. Header Handling and Metadata Extraction
        # ----------------------------------------------------------------------

        # Determine the source participant (Who is calling us?).
        source = request.headers.get("X-Source", "Client")

        # Determine the unique Trace ID.
        trace_id = request.headers.get("X-Trace-ID")
        is_new_trace = False

        if not trace_id:
            # Try traceparent (W3C) - version-traceid-parentid-flags
            # Example: 00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01
            traceparent = request.headers.get("traceparent")
            if traceparent:
                parts = traceparent.split("-")
                if len(parts) >= 2:
                    trace_id = parts[1]

        if not trace_id:
            # Try b3 (Zipkin) - traceid-spanid-sampled-parentspanid
            # Example: 80f198ee56343ba864fe8b2a57d3eff7-e457b5a2e4d86bd1-1-05e3ac9a4f6e3b90
            b3 = request.headers.get("b3")
            if b3:
                # Single header format
                if "-" in b3:
                    trace_id = b3.split("-")[0]
                else:
                    trace_id = b3
            else:
                # Separate header format
                trace_id = request.headers.get("X-B3-TraceId")

        if not trace_id:
            trace_id = str(uuid.uuid4())
            is_new_trace = True

        # Sampling Decision
        if is_new_trace:
            if config.sample_rate < 1.0:
                is_sampled = random.random() < config.sample_rate
            else:
                is_sampled = True
        else:
            # Inherited trace, default to sampled unless we parse flags
            is_sampled = True

        # If not sampled, skip logging but propagate context
        if not is_sampled:
            async with LogContext.ascope(
                {
                    "participant": self.app_name,
                    "trace_id": trace_id,
                    "is_sampled": False,
                }
            ):
                return await call_next(request)

        # Define the action name for the diagram arrow.
        action = f"{request.method} {request.url.path}"

        # Get the configured logger for flow events.
        logger = get_flow_logger()

        # ----------------------------------------------------------------------
        # 2. Log Request Start (Source -> App)
        # ----------------------------------------------------------------------

        # Mask sensitive query params
        params_str = None
        if request.query_params:
            safe_params = data_masker.mask(dict(request.query_params))
            params_str = f"query={safe_params}"

        # Create the 'Request' event representing the call coming into this service.
        req_event = FlowEvent(
            source=source,
            target=self.app_name,
            action=action,
            message=action,
            # Include query parameters in the note if they exist.
            params=params_str,
            trace_id=trace_id,
        )

        # Log the event. This writes the JSON entry that the visualizer will parse.
        logger.info(
            f"{source}->{self.app_name}: {action}", extra={"flow_event": req_event}
        )

        # ----------------------------------------------------------------------
        # 3. Context Setup and Request Processing
        # ----------------------------------------------------------------------

        # Initialize the LogContext for this async task.
        async with LogContext.ascope(
            {"participant": self.app_name, "trace_id": trace_id, "is_sampled": True}
        ):
            start_time = time.time()
            try:
                # Process the request by calling the next item in the middleware chain.
                response = await call_next(request)

                # ------------------------------------------------------------------
                # 4. Log Success Response (App -> Source)
                # ------------------------------------------------------------------

                # Calculate execution time for performance insights.
                duration = (time.time() - start_time) * 1000

                # Create the 'Return' event (dashed line back to caller).
                resp_event = FlowEvent(
                    source=self.app_name,
                    target=source,
                    action=action,
                    message="Return",
                    is_return=True,
                    result=f"{response.status_code} ({duration:.1f}ms)",
                    trace_id=trace_id,
                )
                logger.info(
                    f"{self.app_name}->{source}: Return",
                    extra={"flow_event": resp_event},
                )
                return response

            except Exception as e:
                # ------------------------------------------------------------------
                # 5. Log Error Response (App --x Source)
                # ------------------------------------------------------------------

                # Capture full stack trace for the error.
                stack_trace = "".join(
                    traceback.format_exception(type(e), e, e.__traceback__)
                )

                # If an unhandled exception occurs, log it as an error event.
                err_event = FlowEvent(
                    source=self.app_name,
                    target=source,
                    action=action,
                    message=str(e),
                    is_return=True,
                    is_error=True,
                    error_message=str(e),
                    stack_trace=stack_trace,
                    trace_id=trace_id,
                )
                logger.error(
                    f"{self.app_name}-x{source}: Error", extra={"flow_event": err_event}
                )

                # Re-raise the exception so FastAPI's exception handlers can take over.
                raise
