sequenceDiagram
    title Log Flow
    autonumber

A->>B: Fail
B--xA: Error: oops
note right of A: Traceback (most recent call last):<br/>  File #34;D:\TraeProjects\mermaid-trace\src\mermaid_trace\core\decorators.py#34;, line 659, in wrapper<br/>    result = func(*args, **kwargs)<br/>  File #34;D:\TraeProjects\mermaid-trace\tests\scenarios\test_basic_flow.py#34;, line 47, in fail<br/>    raise ValueError(#34;oops#34;)<br/>ValueError:...
