sequenceDiagram
    title Log Flow
    autonumber

A->>B: Fail
B--xA: Error: oops
note right of A: Traceback (most recent call last):<br/>  File "D:\TraeProjects\mermaid-trace\src\mermaid_trace\core\decorators.py", line 583, in wrapper<br/>    result = func(*args, **kwargs)<br/>  File "D:\TraeProjects\mermaid-trace\tests\scenarios\test_basic_flow.py", line 47, in fail<br/>    raise ValueError("oops")<br/>ValueError:...
