sequenceDiagram
    title Log Flow
    autonumber

User->>App: Main
App->>Processor: Process('')
Processor->>Validator: Validate('')
Validator--xProcessor: Error: Data cannot be empty!
note right of Processor: Traceback (most recent call last):<br/>  File "D:\TraeProjects\mermaid-trace\src\mermaid_trace\core\decorators.py", line 488, in wrapper<br/>    result = func(*args, **kwargs)<br/>  File "D:\TraeProjects\mermaid-trace\examples\04_error_handling.py", line 17, in validate<br/>    raise ValueError("Data cannot be empt...
Processor--xApp: Error: Data cannot be empty!
note right of App: Traceback (most recent call last):<br/>  File "D:\TraeProjects\mermaid-trace\src\mermaid_trace\core\decorators.py", line 488, in wrapper<br/>    result = func(*args, **kwargs)<br/>  File "D:\TraeProjects\mermaid-trace\examples\04_error_handling.py", line 24, in process<br/>    validate(data)<br/>    ~~~~~~~~^^^^^^<br/>  Fi...
App-->>User: Return: None
