sequenceDiagram
    title Log Flow
    autonumber

Client->>MyFastAPI: GET /compute/5
MyFastAPI->>LogicLayer: Calculate Something(5)
LogicLayer-->>MyFastAPI: Return: 500
MyFastAPI-->>Client: Return: 200 (5.7ms)
Client->>MyFastAPI: GET /compute/-1
