sequenceDiagram
    title Log Flow
    autonumber

Client->>WebPortal: POST /users/
WebPortal-->>Client: Return: 422 (1.7ms)
Client->>WebPortal: GET /users/
WebPortal->>WebPortal: List Users Endpoint(db=<Session>)
WebPortal->>UserService: Get Users(<UserService>)
UserService->>Database: SQL: SELECT/QUERY(<Session>, <Select>)
Database-->>UserService: Return: <ChunkedIteratorResult>
UserService-->>WebPortal: Return: [<UserDB> x 6]
