sequenceDiagram
    title Log Flow
    autonumber

Unknown->>PaymentProcessor: Validate Card({}, '1234-5678')
PaymentProcessor-->>Unknown: Return: True
Unknown->>ExternalAPI: HTTP GET('https://api.github.com', timeout=1)
ExternalAPI-->>Unknown: Return: {'connection': {...}, 'cookies': '******', 'elapse...
Unknown->>PaymentProcessor: Charge({}, 99.9)
PaymentProcessor-->>Unknown: Return: 'Charged $99.9'
