from typing import Protocol, Any, Dict, Optional

class LoggerBackend(Protocol):
    """Protocol defining the interface for logger backends."""

    def debug(self, message: str, context: Optional[Dict[str, Any]] = None, **kwargs: Any) -> None: ...
    
    def info(self, message: str, context: Optional[Dict[str, Any]] = None, **kwargs: Any) -> None: ...
    
    def warning(self, message: str, context: Optional[Dict[str, Any]] = None, **kwargs: Any) -> None: ...
    
    def error(self, message: str, context: Optional[Dict[str, Any]] = None, exc_info: bool = False, **kwargs: Any) -> None: ...
    
    def critical(self, message: str, context: Optional[Dict[str, Any]] = None, exc_info: bool = False, **kwargs: Any) -> None: ...

    def configure(self, config: Any) -> None: ...
