sequenceDiagram
    title Log Flow
    autonumber

Outer->>Scope: Fail
Scope--xOuter: Error: Fail
note right of Outer: Traceback (most recent call last):<br/>  File #34;D:\TraeProjects\mermaid-trace\src\mermaid_trace\core\decorators.py#34;, line 659, in wrapper<br/>    result = func(*args, **kwargs)<br/>  File #34;D:\TraeProjects\mermaid-trace\tests\scenarios\test_edge_cases.py#34;, line 75, in fail<br/>    raise ValueError(#34;Fail#34;)<br/>ValueError:...
